#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Boolnut\Core\Inc\Console\GreetingCommand;
use Symfony\Component\Console\Application;

$kernel = new Application();

$commands = [
    GreetingCommand::class,
];

foreach ($commands as $class) {
    if (!class_exists($class)) {
        throw new RuntimeException(sprintf('Class %s does not exist', $class));
    }
    $command = new $class();
    $kernel->add($command);
}

$kernel->run();
